apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flunetd
  labels: 
    app: flunetd
spec:
  selector:
    matchLabels:
      app: flunetd
  template:
    metadata:
      labels:
        app: flunetd
    spec:
      containers:
        - image: fluent/fluentd:v1.17.1-1.0
          name: flunetd-container