apiVersion: v1
kind: Pod
metadata:
  name: web-app01
  labels:
    app: web-app
spec:
  containers:
    - name: web-app-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

---
apiVersion: v1
kind: Pod
metadata:
  name: web-app02
  labels:
    app: web-app
spec:
  containers:
    - name: web-app-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m" 
